Cargo.toml: add more package metadata
Running cargo bitbake to generate a bitbake recipe currently results
in a few error messages due to missing metadata:

  No package.description set in your Cargo.toml, using package.name
  No package.homepage set in your Cargo.toml, trying package.repository
  error: No package.repository set in your Cargo.toml

Fill out these gaps and add some more related keys found while reading
through the documentation at [1].

[1]: https://doc.rust-lang.org/cargo/reference/manifest.html

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>